[package]
name = "nn"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15.1", default-features = false, features = ["bevy_winit", "bevy_render", "bevy_core_pipeline", "bevy_sprite", "x11", "bevy_text","bevy_pbr","tonemapping_luts"] }
bevy_egui = "0.39.1"
burn = { version = "0.20.1", features = ["ndarray", "train"] }
burn-cuda = "0.20.1"
burn-ndarray = "0.20.1"
chrono = { version = "0.4.44", features = ["clock"] }
notify = "8.2.0"
rayon = "1.11.0"
walkdir = "2.5.0"
